ExpressoBundle_homepage:
    pattern:  /setup
    defaults: { _controller: ExpressoBundle:Setup:setup, index: 0 }

ExpressoBundle_setup:
    pattern:  /setup/{index}
    defaults: { _controller: ExpressoBundle:Setup:setup, index: 0 }

ExpressoBundle_final:
    pattern:  /setup/final/
    defaults: { _controller: ExpressoBundle:Setup:final }