REST_Mail_ListFolders:
    pattern:  /ListFolders
    defaults: { _controller: MailBundle:Folder:ListFolders }
    requirements:
            _method:  GET

REST_Mail_getFolder:
    pattern:  /Folder/{folder}
    defaults: { _controller: MailBundle:Folder:ListFolders }
    requirements:
            _method:  GET

REST_Mail_createFolder:
    pattern:  /Folder
    defaults: { _controller: MailBundle:Folder:createFolder }
    requirements:
            _method:  POST

REST_Mail_editFolder:
    pattern:  /Folder/{folder}
    defaults: { _controller: MailBundle:Folder:editFolder }
    requirements:
            _method:  PUT

REST_Mail_deleteFolder:
    pattern:  /Folder/{folder}
    defaults: { _controller: MailBundle:Folder:deleteFolder }
    requirements:
            _method:  DELETE

REST_Mail_ListMessages_Folder:
    pattern:  /ListMessages/Folder/{folder}
    defaults: { _controller: MailBundle:Message:ListMessages }
    requirements:
            _method:  GET

REST_Mail_ListMessages_JqGridFolder:
    pattern:  /jqGridListMessages/Folder/{folder}
    defaults: { _controller: MailBundle:Message:jqGridListMessages }
    requirements:
            _method:  GET

REST_Mail_ListMessages_Folder_Sort:
    pattern:  /ListMessages/Folder/{folder}/Sort/{sort}
    defaults: { _controller: MailBundle:Message:ListMessages }
    requirements:
            _method:  GET

REST_Mail_ListMessages_Folder_Sort_Limit:
    pattern:  /ListMessages/Folder/{folder}/Sort/{sort}/Limit/{limit}
    defaults: { _controller: MailBundle:Message:ListMessages }
    requirements:
            _method:  GET

REST_Mail_ListMessages_Folder_Sort_Limit_Offset:
    pattern:  /ListMessages/Folder/{folder}/Sort/{sort}/Limit/{limit}/Offset/{offset}
    defaults: { _controller: MailBundle:Message:ListMessages }
    requirements:
            _method:  GET